### ISSUE TITLE
Runtime error in optimization.py

### ISSUE THREAD

**Issue by analyticd** [robcarver17/systematictradingexamples#3]
FYI, I ran this in Python 2.7 (which is apparently its implementation target given the use of print without parens) and received this runtime error:

❯ python optimisation.py
Fitting data for 2000-08-31 00:00:00 to 2001-08-31 00:00:00
Traceback (most recent call last):
  File "optimisation.py", line 483, in <module>
    opt_and_plot(data, "expanding", "bootstrap", equalisemeans=False, equalisevols=True)
  File "optimisation.py", line 445, in opt_and_plot
    mat1=optimise_over_periods(*args, **kwargs)
  File "optimisation.py", line 419, in optimise_over_periods
    monte_length=monte_length)
  File "optimisation.py", line 377, in bootstrap_portfolio
    weight=markosolver(returns, equalisemeans=equalisemeans, equalisevols=equalisevols, default_vol=default_vol, default_SR=default_SR)
  File "optimisation.py", line 259, in markosolver
    use_returns=equalise_vols(returns, default_vol)
  File "optimisation.py", line 130, in equalise_vols
    norm_returns.columns=returns.columns
  File "/nix/store/7j6gv6inkj42hchg49n3ad1jdpqv0sv9-python2.7-pandas-0.24.2/lib/python2.7/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/nix/store/7j6gv6inkj42hchg49n3ad1jdpqv0sv9-python2.7-pandas-0.24.2/lib/python2.7/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/nix/store/7j6gv6inkj42hchg49n3ad1jdpqv0sv9-python2.7-pandas-0.24.2/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 6 elements, new values have 3 elements

I also added parens to the print statement and ran under 3.7 and got the same problem.

**Comment by robcarver17** [comment]
Hi
This is pretty old code which I'm no longer maintaining, and I'm guessing what's happened is that the pandas API has changed. I advise you to look at my pysystemtrade project, which is maintained (though the optimisation code needs refactoring, it does work).
